<a href="https://colab.research.google.com/github/nureeee/Machhine-Learning/blob/main/210609_Sklearn_%EA%B0%9C%EC%9A%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 사이킷런
각종 유명한 머신러닝 기법들을 구현해 놓은 **라이브러리**
* 라이브러리(library)란? 도구
* 프레임워크(framework)?
  - 축구장에서는 축구를 하고요.
  - 농구장에선 농구를 하고요
  - 야구장에서는 야구를 할거에요
  - 딥러닝 프레임워크에서는? 딥러닝을 하겠지
  - -> 딥러닝을 하기 위해 필요한 도구들이 준비되어 있는 환경들이 갖춰진 공간


## 훈련하기 - fit
* fit(x, y)
- x : feature
- y : label

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

## LinearRegression 간단 소개
데이터 x가 들어왔을 대 y예측하기 우ㅟ한 기울기와 편향을 학습
$$
y = WX + b
$$

위의 식에서 W :기울기 , b : 편향이라고 한다,
즉 LinearRegression은 y의 오차를 줄이는 W, b를 학습한다



In [2]:
X = np.array([1,2,3,5])
y = np.array([3,5,7,11])

In [3]:
# fit에 대한 이해
model = LinearRegression()
mosel.fit(X, y) # (feature, label)

NameError: ignored

### fit을 할 때는 feature는 무조건 2차원 배열

In [4]:
X.shape

(4,)

In [5]:
X = X.reshape(-1, 1)
X.shape

(4, 1)

In [6]:
X # 2차원 열벡터 
  # 1차원 행벡터는 들어갈 수 없고 2차원 열벡터로 들어갈 수 잇다!!
  # feature의 개수는 4개지만 종류는 1가지(컬럼이 1가지)이다. 

array([[1],
       [2],
       [3],
       [5]])

In [7]:
# 또는 X = X[..., np]

In [9]:
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## 예측하기 - predict
 * 특징
 - predict로 예측할 때는 반드시 훈련시 사용했던 데이터의 스칼라 개수가 맞아야 된다.


In [12]:
#for_predict = np.array([4])  이렇게 하면 안됨 -->행벡터를 열벡터로 만들기
for_predict = np.array([[4], [6]])
for_predict.shape

(2, 1)

In [13]:
model.predict(for_predict)

array([ 9., 13.])

# [번외] LinearRegreeion 모델은 무엇을 어떻게 학습했나?
'w'와 'b'를 학습했다

In [15]:
# w : coef
# b : intercept_

model.coef_

array([2.])

In [16]:
model.intercept_

1.0

## 섭씨-> 화씨 변환 모델 만들기 ( 화씨 예측 모델 만들기)

In [17]:
c = np.arange(1, 20)
f = c * 1.8 + 32


In [18]:
model = LinearRegression()
model.fit(c.reshape(-1, 1), f)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
model.predict(np.array([[30]])) # 섭씨가 30일 때 화씨는 ?

array([86.])

In [20]:
model.coef_

array([1.8])

In [21]:
model.intercept_

32.0